### ISSUE TITLE
Support for configuring the model

### ISSUE THREAD

**Issue by hazzlim** [lunabrain-ai/lunapipe#1]
Hi,

Really awesome tool! I had one suggestion - it would be great to be able to configure which model is used, for example GPT-4, as this doesn't seem to currently be possible. Apologies if I'm wrong about this - I just had a cursory look at the code and it seemed like GPT-3 is hard coded.

Cheers

**Comment by breadchris** [comment]
No you are right, gpt4 support is not fully implemented yet! I have some code started for it, but I can whip that out 👍

**Comment by hazzlim** [comment]
Cheers dude! I’m completely inexperienced in Go, but I’m keen to get to grips with it and make some contributions to the project

**Comment by hazzlim** [comment]
Ah in fact - looks like the project you are using for OpenAI API interaction, PullRequestInc/go-gpt3, only supports the old “engine” endpoints and not the new “model” endpoints - perhaps the code you started is migrating to a different project / interfacing with the APIs directly?

**Comment by breadchris** [comment]
oh interesting catch, I am not familiar with that distinction. Do you have a link that explains the difference/how I can implement it? From a brief search I can't see anything, I can dive into the API docs later, but maybe you can save me some time :)

**Comment by hazzlim** [comment]
So the ```engines API``` [was deprecated](https://help.openai.com/en/articles/6283125-what-happened-to-engines) in favour of [```models```](https://platform.openai.com/docs/models) - which to be fair seems to largely be a naming difference in the endpoint URL paths. From what I read - and from my testing - it seems as though the old endpoints still work and accept the newer models.

Looks like ```PullRequestInc/go-gpt3``` are still using the old endpoints - although there is a [PR to address this](https://github.com/PullRequestInc/go-gpt3/pull/20), it looks like it may have been abandoned mid-review. Either way - the upside is that it looks like the ```model``` can simply be specified in the ```ChatCompletionRequest```, for example the below:

https://github.com/lunabrain-ai/lunapipe/blob/d1450e0abffebb4d4095978099f899e538906f99/internal/openai.go#L93-L98

can be modified to:

```
 req := gpt3.ChatCompletionRequest{ 
        Model: model_string,
 	Temperature: float32(0), 
 	MaxTokens:   respTokenCount, 
 	Stream:      stream, 
 	Messages:    chatCtx, 
 } 
```

where ```model string``` is the name of any of the models supporting the ```/v1/chat/completions``` endpoint ([documented here](/v1/chat/completions)).

Again, thanks for working on this super cool project! I should really learn some go ... I got a bit stumped for a second there with some "slice literal" related errors haha.

**Comment by hazzlim** [comment]
Also, its somewhat amusing to me to be using a module called "gpt3" to access gpt-4 models... I feel as though they should have named that project something a bit more future-proof 😆

**Comment by breadchris** [comment]
awesome, thanks for the deets. Unlucky that the PR looks stale. Perhaps it would be worthwhile to use a more actively maintained client like https://github.com/sashabaranov/go-openai

**Comment by breadchris** [comment]
You can run `lunapipe -m gpt-4 "Read values from map"` now, as well as stick it in your config:

```
openai:
  api_key: xxx
  timeout: 5m0s
  model: gpt-4
```

**Comment by hazzlim** [comment]
Nice one! Thanks for getting that in so quickly :)
